const axios = require('axios');
const bcrypt = require('bcrypt');
const { Order, Product, User } = require('./models/index');

const dummyOrders = [
    {
        userId: '613fd5fb5c15a81711e95c13',
        items: [
            { productId: '60b5ead6f502a40022b26d0b', quantity: 2, price: 3000 },
            { productId: '60b5ead6f502a40022b26d0c', quantity: 3, price: 4000 },
        ],
        orderInfo: {
            orderNumber: '20230001',
            totalPrice: 19000,
        },
        deliveryInfo: {
            receiverName: 'Alice Kim',
            receiverPhone: '010-1234-5678',
            address: '1234 Example St',
            postCode: '12345',
        },
        deliveryStatus: 'processing',
    },
    {
        userId: '613fd5fb5c15a81711e95c14',
        items: [
            { productId: '60b5ead6f502a40022b26d0d', quantity: 1, price: 3000 },
            { productId: '60b5ead6f502a40022b26d0e', quantity: 4, price: 4000 },
        ],
        orderInfo: {
            orderNumber: '20230002',
            totalPrice: 19000,
        },
        deliveryInfo: {
            receiverName: 'Bob Lee',
            receiverPhone: '010-2345-6789',
            address: '5678 Example St',
            postCode: '23456',
        },
        deliveryStatus: 'delivered',
    },
    {
        userId: '613fd5fb5c15a81711e95c15',
        items: [
            { productId: '60b5ead6f502a40022b26d0f', quantity: 3, price: 5000 },
            { productId: '60b5ead6f502a40022b26d10', quantity: 2, price: 6000 },
        ],
        orderInfo: {
            orderNumber: '20230003',
            totalPrice: 27000,
        },
        deliveryInfo: {
            receiverName: 'Charlie Park',
            receiverPhone: '010-3456-7890',
            address: '9012 Example St',
            postCode: '34567',
        },
        deliveryStatus: 'processing',
    },
    {
        userId: '613fd5fb5c15a81711e95c16',
        items: [
            { productId: '60b5ead6f502a40022b26d11', quantity: 1, price: 7000 },
            { productId: '60b5ead6f502a40022b26d12', quantity: 2, price: 8000 },
        ],
        orderInfo: {
            orderNumber: '20230004',
            totalPrice: 23000,
        },
        deliveryInfo: {
            receiverName: 'David Kim',
            receiverPhone: '010-4567-8901',
            address: '2345 Example St',
            postCode: '45678',
        },
        deliveryStatus: 'delivered',
    },
];

const insertDummyOrders = async () => {
    try {
        await Order.deleteMany({}, { maxTimeMS: 60000 });
        await Order.create(dummyOrders);
        console.log('Dummy orders inserted successfully');
    } catch (error) {
        console.log('Error inserting dummy orders: ', error);
    }
};

const dummyProducts = [
    {
        productId: 1,
        title: '위대한 개츠비',
        author: 'F. 스콧 피츠제럴드',
        price: 12000,
        category: '소설',
        introduction: '부자 제이 개츠비와 아름다운 데이지 부캐넌에 대한 사랑 이야기.',
        imgUrl: 'https://example.com/gatsby.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '스크리브너',
    },
    {
        productId: 2,
        title: '진달래꽃',
        author: '하퍼 리',
        price: 15000,
        category: '소설',
        introduction:
            '1930년대 앨라배마의 한 마을에서 성장하는 어린 소녀가 남부에서의 불공평과 인종차별을 알게 된다.',
        imgUrl: 'https://example.com/mockingbird.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: 'J.B. 리핀콧 앤 코.',
    },
    {
        productId: 3,
        title: '호밀밭의 파수꾼',
        author: 'J.D. 샐린저',
        price: 18000,
        category: '소설',
        introduction: '홀든 코울필드라는 청소년이 사회의 소외와 환멸을 경험하는 이야기.',
        imgUrl: 'https://example.com/catcher.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '리틀, 브라운 앤 컴퍼니',
    },
    {
        productId: 4,
        title: '1984',
        author: '조지 오웰',
        price: 20000,
        category: '소설',
        introduction:
            '정부가 시민들의 삶의 모든 면을 통제하는 토탈리타리즘 사회에서 벌어지는 디스토피아 소설.',
        imgUrl: 'https://example.com/1984.jpg',
        bestSeller: true,
        newBook: false,
        recommend: false,
        publisher: '섹커 앤 워버그',
    },
    {
        productId: 5,
        title: '호빗',
        author: 'J.R.R. 톨킨',
        price: 25000,
        category: '소설',
        introduction:
            '드래곤에게 훔쳐진 보물을 되찾기 위해 모험을 떠나는 호빗 빌보 백긴스의 이야기.',
        imgUrl: 'https://example.com/hobbit.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '알렌 & 언윈',
    },
    {
        productId: 6,
        title: '자존감 수업',
        author: '윤홍균',
        price: 13000,
        category: '자기계발',
        introduction: '자존감을 높여 성공과 행복을 이끌어내는 방법을 알려주는 실용적인 자기계발서.',
        imgUrl: 'https://example.com/selfesteem.jpg',
        bestSeller: false,
        newBook: true,
        recommend: true,
        publisher: '메이븐',
    },
    {
        productId: 7,
        title: '창문 넘어 도망친 100세 노인',
        author: '요나스 요나손',
        price: 12000,
        category: '소설',
        introduction: '100세 노인이 창문을 통해 도망쳐 벌어지는 유쾌하고 흥미진진한 모험 이야기.',
        imgUrl: 'https://example.com/100yearold.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '시공사',
    },
    {
        productId: 8,
        title: '나미야 잡화점의 기적',
        author: '히가시노 게이고',
        price: 14000,
        category: '소설',
        introduction: '시간과 공간을 초월하는 편지들을 통해 인생의 의미를 찾아가는 따뜻한 이야기.',
        imgUrl: 'https://example.com/namiya.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '현대문학',
    },
    {
        productId: 9,
        title: '어린 왕자',
        author: '생텍쥐페리',
        price: 10000,
        category: '소설',
        introduction:
            '어린 왕자와 함께 우주를 여행하며 인간의 본질을 탐구하는 독특한 이야기입니다.',
        imgUrl: 'https://example.com/littleprince.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '미늄사',
    },
    {
        productId: 10,
        title: '토지',
        author: '박경리',
        price: 15000,
        category: '소설',
        introduction: '한국의 역사와 농민의 삶을 소재로 한 대표적인 민주화 소설.',
        imgUrl: 'https://example.com/toji.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '민음사',
    },
    {
        productId: 11,
        title: '데미안',
        author: '헤르만 헤세',
        price: 12000,
        category: '소설',
        introduction: '청년 시절의 자아를 찾아가는 이야기를 통해 인간의 성장과 정신 세계를 탐구.',
        imgUrl: 'https://example.com/demian.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '민음사',
    },
    {
        productId: 12,
        title: '백설공주',
        author: '그림 형제',
        price: 10000,
        category: '동화',
        introduction: '백설공주와 일곱 난장이의 동화적인 모험 이야기.',
        imgUrl: 'https://example.com/snowwhite.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '한국문학방송출판사',
    },
    {
        productId: 13,
        title: '빨강 머리 앤',
        author: '루시 모드 몽고메리',
        price: 15000,
        category: '소설',
        introduction:
            '고아인 앤이 자랑스러운 성격과 사랑스러운 빨간 머리를 통해 인생의 가르침을 얻는 이야기.',
        imgUrl: 'https://example.com/anneofgreengables.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '서울문화사',
    },
    {
        productId: 14,
        title: '걸리버 여행기',
        author: '조나단 스위프트',
        price: 13000,
        category: '소설',
        introduction: '걸리버가 여러 이상한 세계로 여행하며 겪는 유쾌한 모험 이야기.',
        imgUrl: 'https://example.com/gulliverstravels.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '영미출판사',
    },
    {
        productId: 15,
        title: '나의 라임 오렌지나무',
        author: '조제 마우로 데 바스콘셀로스',
        price: 11000,
        category: '소설',
        introduction: '빈곤한 환경에서도 인간미와 사랑을 발견하는 소년의 감동적인 이야기.',
        imgUrl: 'https://example.com/mylimeorangetree.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '자음과모음',
    },
    {
        productId: 16,
        title: '이방인',
        author: '알베르 카뮈',
        price: 14000,
        category: '소설',
        introduction: '인간과 사회의 이질감을 다룬 소설로, 주인공의 관점에서 이야기가 펼쳐진다.',
        imgUrl: 'https://example.com/theoutsider.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '문학동네',
    },
    {
        productId: 17,
        title: '돌이킬 수 없는 강',
        author: '퍼시 발록 슈타인벡',
        price: 15000,
        category: '소설',
        introduction: '농부들의 땅과 가족에 대한 투쟁과 이야기를 그린 소설.',
        imgUrl: 'https://example.com/theunstoppable.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '현대문학',
    },
    {
        productId: 18,
        title: '미움받을 용기',
        author: '기시미 이치로',
        price: 16000,
        category: '자기계발',
        introduction: '인간의 본질에 대해 탐구하며 자신을 찾아가는 과정을 다룬 도서.',
        imgUrl: 'https://example.com/courage.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '인플루엔셜',
    },
    {
        productId: 19,
        title: '세상에서 가장 아름다운 이별',
        author: '신경숙',
        price: 12000,
        category: '소설',
        introduction: '가족과 사랑에 대한 이야기로, 인간의 삶과 이별을 아름답게 그린 소설.',
        imgUrl: 'https://example.com/beautifulgoodbye.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '마음의숲',
    },
    {
        productId: 20,
        title: '해리 포터와 마법사의 돌',
        author: 'J.K. 롤링',
        price: 17000,
        category: '소설',
        introduction: '마법의 세계에서 모험을 겪는 해리 포터와 친구들의 이야기의 시작.',
        imgUrl: 'https://example.com/harrypotter1.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '문학수첩',
    },
    {
        productId: 21,
        title: '데미안',
        author: '헤르만 헤세',
        price: 13000,
        category: '소설',
        introduction: '주인공의 성장과 자아를 찾아가는 과정을 그린 소설.',
        imgUrl: 'https://example.com/demian.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '민음사',
    },
    {
        productId: 22,
        title: '칼데아의 이발사',
        author: '토마스 맨',
        price: 11000,
        category: '소설',
        introduction: '철학적인 통찰을 담은 이야기로, 인간의 운명과 행복에 대해 다룬다.',
        imgUrl: 'https://example.com/barber.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '걷는나무',
    },
    {
        productId: 23,
        title: '슬로우',
        author: '김한',
        price: 15000,
        category: '에세이',
        introduction: '세상의 빠른 흐름 속에서 천천히 걷는 것의 소중함을 담은 에세이.',
        imgUrl: 'https://example.com/slow.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '더날',
    },
    {
        productId: 24,
        title: '여행의 이유',
        author: '김영하',
        price: 14000,
        category: '에세이',
        introduction: '세계 여러 곳을 여행하며 겪은 경험과 그곳에서 얻은 인사이트를 담은 에세이.',
        imgUrl: 'https://example.com/reasonfortravel.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '문학동네',
    },
    {
        productId: 25,
        title: '책상 위의 여행',
        author: '김영아',
        price: 16000,
        category: '에세이',
        introduction: '여행지와 책, 글쓰기를 통해 세상을 바라보는 작가의 시선을 담은 에세이.',
        imgUrl: 'https://example.com/desktravel.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '문학수첩',
    },
    {
        productId: 26,
        title: '미라클 모닝',
        author: '할 엘로드',
        price: 19000,
        category: '자기계발',
        introduction: '아침에 일어나는 습관을 통해 성공과 행복을 이루는 방법을 담은 자기계발서.',
        imgUrl: 'https://example.com/miracle.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '인플루엔셜',
    },
    {
        productId: 27,
        title: '세상을 바꾼 유튜버들',
        author: '김신영',
        price: 12000,
        category: '사회',
        introduction:
            '온라인 동영상 공유 서비스인 유튜브를 통해 사회를 바꾼 일부 유튜버들의 이야기',
        imgUrl: 'https://example.com/youtubers.jpg',
        bestSeller: false,
        newBook: true,
        recommend: true,
        publisher: '창비',
    },
    {
        productId: 28,
        title: '방구석 여행자의 세계 일주',
        author: '이성규',
        price: 18000,
        category: '여행',
        introduction: '편안한 방에서 즐기는 세계 일주 여행 기록과 팁',
        imgUrl: 'https://example.com/armchairtraveler.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '위즈덤하우스',
    },
    {
        productId: 29,
        title: '강의력',
        author: '장성옥',
        price: 17000,
        category: '경영/리더십',
        introduction: '강의와 프리젠테이션을 효과적으로 하기 위한 팁과 기술',
        imgUrl: 'https://example.com/presentation.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '토네이도',
    },
    {
        productId: 30,
        title: '여름의 빛',
        author: '김연수',
        price: 15000,
        category: '소설',
        introduction: '여름에 빛나는 세 사람의 이야기',
        imgUrl: 'https://example.com/summerlight.jpg',
        bestSeller: false,
        newBook: false,
        recommend: false,
        publisher: '문학동네',
    },
    {
        productId: 31,
        title: '나의 정신 건강 이야기',
        author: '이민혁',
        price: 22000,
        category: '자기계발',
        introduction: '작가 본인의 정신 건강 이야기와 자기 회복에 대한 경험담',
        imgUrl: 'https://example.com/mentalhealth.jpg',
        bestSeller: true,
        newBook: true,
        recommend: false,
        publisher: '쌤앤파커스',
    },
    {
        productId: 32,
        title: '내가 그린 고양이',
        author: '이지성',
        price: 10000,
        category: '그림책',
        introduction: '자신만의 방식으로 고양이를 그리는 아이들의 이야기와 작품 모음집',
        imgUrl: 'https://example.com/mycat.jpg',
        bestSeller: false,
        newBook: true,
        recommend: true,
        publisher: '하이미디어',
    },
    {
        productId: 33,
        title: '왜 오늘은 안 되지?',
        author: '이영세',
        price: 15000,
        category: '자기계발',
        introduction: '몰입력, 목표 달성, 즉각성 등을 높이기 위한 생산성 개선 방법',
        imgUrl: 'https://example.com/productivity.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '알에이치코리아',
    },
    {
        productId: 34,
        title: '물빛 이야기',
        author: '이은석',
        price: 16000,
        category: '소설',
        introduction: '작가의 고향인 제주도의 이야기를 담은 인간의 성장 이야기',
        imgUrl: 'https://example.com/waterlight.jpg',
        bestSeller: false,
        newBook: false,
        recommend: false,
        publisher: '문학수첩',
    },
    {
        productId: 35,
        title: '미묘한 깨달음',
        author: '선우경호',
        price: 20000,
        category: '철학',
        introduction: '사람의 삶과 진리에 대한 탐구를 담은 철학서',
        imgUrl: 'https://example.com/enlightenment.jpg',
        bestSeller: true,
        newBook: true,
        recommend: true,
        publisher: '정신세계사',
    },
    {
        productId: 36,
        title: '창작의 기술',
        author: '짐 헨슨',
        price: 25000,
        category: '창작',
        introduction: '창작에 필요한 기술과 전략을 설명하는 창작서',
        imgUrl: 'https://example.com/creativity.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '한빛미디어',
    },
    {
        productId: 37,
        title: '매니저 대신 상사가 되는 법',
        author: '유석영',
        price: 22000,
        category: '경영/리더십',
        introduction: '매니저와 상사의 차이점과 상사가 되기 위한 실용적인 방법',
        imgUrl: 'https://example.com/boss.jpg',
        bestSeller: true,
        newBook: true,
        recommend: true,
        publisher: '토네이도',
    },
    {
        productId: 38,
        title: '비폭력의 힘',
        author: '마하트마 간디',
        price: 12000,
        category: '사회',
        introduction: '간디의 비폭력주의 이론과 그것을 실천한 인물들의 이야기',
        imgUrl: 'https://example.com/nonviolence.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '열린책들',
    },
    {
        productId: 39,
        title: '강철의 인내',
        author: '키스케 야마구치',
        price: 18000,
        category: '자기계발',
        introduction: '철물점에서 노동자로 일하며 강한 인내력을 길러낸 작가의 경험담',
        imgUrl: 'https://example.com/perseverance.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '창비',
    },
    {
        productId: 40,
        title: '마법의 습관',
        author: '제임스 클리어',
        price: 25000,
        category: '자기계발',
        introduction: '습관을 바꾸어 성공적인 삶을 살기 위한 방법과 예시를 제시하는 자기계발서',
        imgUrl: 'https://example.com/habits.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '쌤앤파커스',
    },
    {
        productId: 41,
        title: '사이코패스 체험',
        author: '김준',
        price: 20000,
        category: '심리학',
        introduction: '사이코패스를 인식하고 대처하는 방법을 제시하는 심리학서',
        imgUrl: 'https://example.com/psychopath.jpg',
        bestSeller: true,
        newBook: true,
        recommend: false,
        publisher: '밝은세상',
    },
    {
        productId: 42,
        title: '여름이 가기 전에',
        author: '김난도',
        price: 15000,
        category: '소설',
        introduction: '휴가를 맞이해 여름 바다로 떠나는 부부의 이야기',
        imgUrl: 'https://example.com/summertime.jpg',
        bestSeller: false,
        newBook: false,
        recommend: true,
        publisher: '문학동네',
    },
    {
        productId: 43,
        title: '그림의 힘',
        author: '베트 나이만',
        price: 30000,
        category: '창작',
        introduction: '그림으로 자신의 내면을 탐구하고 창조적인 생각을 유도하는 창작서',
        imgUrl: 'https://example.com/drawingpower.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '북스톤',
    },
    {
        productId: 44,
        title: '나는 스마트폰 중독자입니다',
        author: '이현주',
        price: 17000,
        category: '자기계발',
        introduction: '스마트폰 중독을 극복하기 위한 방법과 체험담',
        imgUrl: 'https://example.com/smartphoneaddict.jpg',
        bestSeller: true,
        newBook: true,
        recommend: true,
        publisher: '흐름출판사',
    },
    {
        productId: 45,
        title: '일본 아빠와의 대화',
        author: '유대영',
        price: 20000,
        category: '에세이',
        introduction: '일본 아빠와의 인연과 대화를 통해 발견한 인생의 진리',
        imgUrl: 'https://example.com/japanesedad.jpg',
        bestSeller: true,
        newBook: true,
        recommend: false,
        publisher: '북라이프',
    },
    {
        productId: 46,
        title: '골목길 인생',
        author: '이기황',
        price: 13000,
        category: '에세이',
        introduction: '서울의 다양한 골목길을 찾아다니며 만난 사람들과 이야기하는 인생 이야기',
        imgUrl: 'https://example.com/streetlife.jpg',
        bestSeller: false,
        newBook: true,
        recommend: true,
        publisher: '비즈니스북스',
    },
    {
        productId: 47,
        title: '행복한 마음',
        author: '토니 헤일',
        price: 25000,
        category: '자기계발',
        introduction: '행복을 찾기 위한 마음의 방법과 연습법을 설명하는 자기계발서',
        imgUrl: 'https://example.com/happiness.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '페이지2',
    },
    {
        productId: 48,
        title: '우리가 빛나는 순간',
        author: '구리현',
        price: 16000,
        category: '에세이',
        introduction: '인생에서 가장 빛나는 순간과 그에 대한 인사이트를 담은 에세이 모음집',
        imgUrl: 'https://example.com/shiningmoment.jpg',
        bestSeller: true,
        newBook: false,
        recommend: true,
        publisher: '봄날출판사',
    },
    {
        productId: 49,
        title: '엔트리 레벨',
        author: '이종원',
        price: 20000,
        category: '소설',
        introduction: 'IT 취업을 꿈꾸는 청년들의 성장 이야기',
        imgUrl: 'https://example.com/entrylevel.jpg',
        bestSeller: true,
        newBook: true,
        recommend: false,
        publisher: '어크로스',
    },
    {
        productId: 50,
        title: '우울할 땐 어떻게 해야 할까?',
        author: '다이언 쿠미',
        price: 18000,
        category: '자기계발',
        introduction: '우울증에 대한 이해와 극복 방법을 제시하는 자기계발서',
        imgUrl: 'https://example.com/depression.jpg',
        bestSeller: true,
        newBook: true,
        recommend: true,
        publisher: '메이븐포트',
    },
];

const insertDummyProducts = async () => {
    try {
        await Product.deleteMany({}, { maxTimeMS: 60000 });
        await Product.create(dummyProducts);
        console.log('Dummy products inserted successfully');
    } catch (error) {
        console.log('Error inserting dummy products: ', error);
    }
};

const dummyUsers = [
    {
        userId: 'user1',
        password: bcrypt.hashSync('password1', 10),
        email: 'user1@example.com',
        userName: 'John Doe',
        role: 'user',
        tokens: {
            accessToken: 'dummy_access_token_1',
            refreshToken: 'dummy_refresh_token_1',
        },
    },
    {
        userId: 'admin1',
        password: bcrypt.hashSync('password1', 10),
        email: 'admin1@example.com',
        userName: 'Jane Doe',
        role: 'admin',
        tokens: {
            accessToken: 'dummy_access_token_2',
            refreshToken: 'dummy_refresh_token_2',
        },
    },
    {
        userId: 'user2',
        password: bcrypt.hashSync('password2', 10),
        email: 'user2@example.com',
        userName: 'Alice',
        role: 'user',
        tokens: {
            accessToken: 'dummy_access_token_3',
            refreshToken: 'dummy_refresh_token_3',
        },
    },
    {
        userId: 'admin2',
        password: bcrypt.hashSync('password2', 10),
        email: 'admin2@example.com',
        userName: 'Bob',
        role: 'admin',
        tokens: {
            accessToken: 'dummy_access_token_4',
            refreshToken: 'dummy_refresh_token_4',
        },
    },
    {
        userId: 'user3',
        password: bcrypt.hashSync('password3', 10),
        email: 'user3@example.com',
        userName: 'Eve',
        role: 'user',
        tokens: {
            accessToken: 'dummy_access_token_5',
            refreshToken: 'dummy_refresh_token_5',
        },
    },
];

const insertDummyUsers = async () => {
    try {
        await User.deleteMany({});
        await User.create(dummyUsers);
        console.log('Dummy users inserted successfully');
    } catch (error) {
        console.error(error);
    }
};

module.exports = { insertDummyUsers, insertDummyProducts, insertDummyOrders };
